/**
 * Skill Installer
 * スキルのインストール・アンインストール処理
 */
import * as fs from "fs/promises";
import * as path from "path";
import { resolveTrustedWorkspacePath, validateSkillName } from "./workspace.js";

/** インストール結果 */
export interface InstallResult {
  success: boolean;
  skillName: string;
  installPath: string;
  message: string;
}

const AGENTS_SECTION_START = "<!-- skill-ninja:installed-skills:start -->";
const AGENTS_SECTION_END = "<!-- skill-ninja:installed-skills:end -->";
const AGENTS_FOOTER = "*Auto-generated by Agent Skill Ninja*";

function buildManagedAgentsSection(installedSkills: string[]): string {
  const lines = [AGENTS_SECTION_START, "## Installed Skills", ""];

  for (const skill of installedSkills) {
    lines.push(`- [${skill}](.github/skills/${skill}/SKILL.md)`);
  }

  lines.push("");
  lines.push("---");
  lines.push(AGENTS_FOOTER);
  lines.push(AGENTS_SECTION_END);

  return lines.join("\n");
}

function buildStandaloneAgentsMd(installedSkills: string[]): string {
  return [
    "# Agent Skills",
    "",
    "This file lists installed agent skills.",
    "",
    buildManagedAgentsSection(installedSkills),
  ].join("\n");
}

function isLegacyGeneratedAgentsMd(content: string): boolean {
  return (
    content.includes("# Agent Skills") &&
    content.includes("## Installed Skills") &&
    content.includes(AGENTS_FOOTER) &&
    !content.includes(AGENTS_SECTION_START)
  );
}

function removeManagedAgentsSection(content: string): string {
  const sectionPattern = new RegExp(
    `\\n?${AGENTS_SECTION_START}[\\s\\S]*?${AGENTS_SECTION_END}\\n?`,
    "m",
  );

  return content
    .replace(sectionPattern, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

async function readAgentsMd(agentsPath: string): Promise<string | null> {
  try {
    return await fs.readFile(agentsPath, "utf-8");
  } catch {
    return null;
  }
}

/**
 * スキルをワークスペースにインストール
 */
export async function installSkill(
  skillName: string,
  skillContent: string,
  workspacePath: string,
): Promise<InstallResult> {
  const trustedWorkspacePath = await resolveTrustedWorkspacePath(workspacePath);
  const safeSkillName = validateSkillName(skillName);
  const skillsDir = path.join(
    trustedWorkspacePath,
    ".github",
    "skills",
    safeSkillName,
  );
  const skillFilePath = path.join(skillsDir, "SKILL.md");

  try {
    // ディレクトリを作成
    await fs.mkdir(skillsDir, { recursive: true });

    // SKILL.md を書き込み
    await fs.writeFile(skillFilePath, skillContent, "utf-8");

    return {
      success: true,
      skillName,
      installPath: skillsDir,
      message: `Successfully installed ${skillName}`,
    };
  } catch (error) {
    return {
      success: false,
      skillName,
      installPath: skillsDir,
      message: `Failed to install ${skillName}: ${error}`,
    };
  }
}

/**
 * スキルをアンインストール
 */
export async function uninstallSkill(
  skillName: string,
  workspacePath: string,
): Promise<InstallResult> {
  const trustedWorkspacePath = await resolveTrustedWorkspacePath(workspacePath);
  const safeSkillName = validateSkillName(skillName);
  const skillsDir = path.join(
    trustedWorkspacePath,
    ".github",
    "skills",
    safeSkillName,
  );

  try {
    // ディレクトリを削除
    await fs.rm(skillsDir, { recursive: true, force: true });

    return {
      success: true,
      skillName,
      installPath: skillsDir,
      message: `Successfully uninstalled ${skillName}`,
    };
  } catch (error) {
    return {
      success: false,
      skillName,
      installPath: skillsDir,
      message: `Failed to uninstall ${skillName}: ${error}`,
    };
  }
}

/**
 * インストール済みスキル一覧を取得
 */
export async function getInstalledSkills(
  workspacePath: string,
): Promise<string[]> {
  const trustedWorkspacePath = await resolveTrustedWorkspacePath(workspacePath);
  const skillsDir = path.join(trustedWorkspacePath, ".github", "skills");

  try {
    const entries = await fs.readdir(skillsDir, { withFileTypes: true });
    const skills: string[] = [];

    for (const entry of entries) {
      if (entry.isDirectory()) {
        // SKILL.md が存在するか確認
        const skillFile = path.join(skillsDir, entry.name, "SKILL.md");
        try {
          await fs.access(skillFile);
          skills.push(entry.name);
        } catch {
          // SKILL.md がなければスキップ
        }
      }
    }

    return skills;
  } catch {
    // ディレクトリが存在しない場合は空配列
    return [];
  }
}

/**
 * AGENTS.md を更新
 */
export async function updateAgentsMd(workspacePath: string): Promise<void> {
  const trustedWorkspacePath = await resolveTrustedWorkspacePath(workspacePath);
  const agentsPath = path.join(trustedWorkspacePath, "AGENTS.md");
  const installedSkills = await getInstalledSkills(trustedWorkspacePath);
  const existingContent = await readAgentsMd(agentsPath);

  if (installedSkills.length === 0) {
    if (!existingContent) {
      return;
    }

    if (existingContent.includes(AGENTS_SECTION_START)) {
      const nextContent = removeManagedAgentsSection(existingContent);
      if (!nextContent) {
        await fs.unlink(agentsPath);
      } else {
        await fs.writeFile(agentsPath, `${nextContent}\n`, "utf-8");
      }
      return;
    }

    if (isLegacyGeneratedAgentsMd(existingContent)) {
      await fs.unlink(agentsPath);
    }

    return;
  }

  const managedSection = buildManagedAgentsSection(installedSkills);

  if (!existingContent || isLegacyGeneratedAgentsMd(existingContent)) {
    await fs.writeFile(
      agentsPath,
      `${buildStandaloneAgentsMd(installedSkills)}\n`,
      "utf-8",
    );
    return;
  }

  const nextContent = existingContent.includes(AGENTS_SECTION_START)
    ? existingContent.replace(
        new RegExp(
          `${AGENTS_SECTION_START}[\\s\\S]*?${AGENTS_SECTION_END}`,
          "m",
        ),
        managedSection,
      )
    : `${existingContent.trimEnd()}\n\n${managedSection}\n`;

  await fs.writeFile(agentsPath, nextContent, "utf-8");
}
